# Generated by Django 4.2.7 on 2025-10-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Placed'), ('confirmed', 'Order Confirmed'), ('processing', 'Preparing Order'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('pending', 'Order Placed'), ('confirmed', 'Order Confirmed'), ('processing', 'Preparing Order'), ('ready_for_pickup', 'Ready for Pickup'), ('shipped', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
