# Generated by Django 4.2.7 on 2025-11-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_create_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ad_type', models.CharField(choices=[('video', 'Video Advertisement'), ('banner', 'Banner/Poster')], max_length=10)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4, WebM, or OGV video files', null=True, upload_to='advertisements/videos/')),
                ('video_url', models.URLField(blank=True, help_text='Or provide a YouTube/Vimeo URL', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/banners/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which ads are displayed (lower numbers first)')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Advertisements',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
